name: Sync branch

on:
  push:
    branches: [feat/CICD]

jobs:
  sync_job:
    runs-on: ubuntu-latest
    steps:
      - name: Sync ${{ github.ref }} to dev
        uses: devmasx/merge-branch@dev
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          type: now
          from_branch: ${{ github.ref }}
          target_branch: dev

      - name: Sync dev with main
        uses: devmasx/merge-branch@main
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          type: now
          from_branch: dev
          target_branch: main

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: release

      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
